"""Initial migration

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2023-12-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_checkpoints',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_run_id', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_checkpoints_id'), 'etl_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_etl_checkpoints_source'), 'etl_checkpoints', ['source'], unique=True)

    op.create_table('etl_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('run_id', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('records_processed', sa.Integer(), nullable=True),
        sa.Column('duration_ms', sa.Float(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_runs_id'), 'etl_runs', ['id'], unique=False)
    op.create_index(op.f('ix_etl_runs_run_id'), 'etl_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_etl_runs_source'), 'etl_runs', ['source'], unique=False)

    op.create_table('raw_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('content', sa.JSON(), nullable=True),
        sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_data_external_id'), 'raw_data', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_data_id'), 'raw_data', ['id'], unique=False)
    op.create_index(op.f('ix_raw_data_source'), 'raw_data', ['source'], unique=False)

    op.create_table('unified_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unified_data_external_id'), 'unified_data', ['external_id'], unique=True)
    op.create_index(op.f('ix_unified_data_id'), 'unified_data', ['id'], unique=False)
    op.create_index(op.f('ix_unified_data_source'), 'unified_data', ['source'], unique=False)
    op.create_index(op.f('ix_unified_data_title'), 'unified_data', ['title'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_data_title'), table_name='unified_data')
    op.drop_index(op.f('ix_unified_data_source'), table_name='unified_data')
    op.drop_index(op.f('ix_unified_data_id'), table_name='unified_data')
    op.drop_index(op.f('ix_unified_data_external_id'), table_name='unified_data')
    op.drop_table('unified_data')
    op.drop_index(op.f('ix_raw_data_source'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_id'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_external_id'), table_name='raw_data')
    op.drop_table('raw_data')
    op.drop_index(op.f('ix_etl_runs_source'), table_name='etl_runs')
    op.drop_index(op.f('ix_etl_runs_run_id'), table_name='etl_runs')
    op.drop_index(op.f('ix_etl_runs_id'), table_name='etl_runs')
    op.drop_table('etl_runs')
    op.drop_index(op.f('ix_etl_checkpoints_source'), table_name='etl_checkpoints')
    op.drop_index(op.f('ix_etl_checkpoints_id'), table_name='etl_checkpoints')
    op.drop_table('etl_checkpoints')
    # ### end Alembic commands ###
